# Generated by Django 3.0.7 on 2020-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_professors_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='role',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Professor', 'Professor')], default='Professor', max_length=20),
        ),
    ]
