# Generated by Django 3.0.7 on 2020-06-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_professors_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
